# Generated by Django 5.0.2 on 2024-02-08 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Category Name', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Tag Name', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Content Title', max_length=100)),
                ('description', models.TextField(help_text='Description of content you are adding')),
                ('file', models.FileField(upload_to='content-files')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_contents', to='src.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_contents', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='tag_contents', to='src.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
