# Generated by Django 5.0.2 on 2024-02-09 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_content_dislikes_content_likes_content_shares_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='src.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
