# Generated by Django 5.0.2 on 2024-02-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_remove_content_attributes_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_attributes',
            name='is_like',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
